In [1]:
import pandas as pd
import numpy as np

### MISSING DATA

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna()
# None is also treated as NA

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [5]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()


0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
# same as above cell
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
# will drop the entire row if it contains a NA value 
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [9]:
# will only drop a row if the entire row is NA
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
data.dropna(axis='columns', how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  0.265736       NaN       NaN
1  0.057767       NaN       NaN
2  0.398779       NaN  0.025354
3  0.632846       NaN  0.113368
4 -0.637273  1.049105  0.958093
5  0.020529  0.520461  0.738375
6 -1.149914  1.244016  1.318667

In [12]:
df.dropna()

0         1         2
4 -0.637273  1.049105  0.958093
5  0.020529  0.520461  0.738375
6 -1.149914  1.244016  1.318667

In [13]:
df.dropna(thresh=2)

0         1         2
2  0.398779       NaN  0.025354
3  0.632846       NaN  0.113368
4 -0.637273  1.049105  0.958093
5  0.020529  0.520461  0.738375
6 -1.149914  1.244016  1.318667

In [14]:
df.fillna(0)

0         1         2
0  0.265736  0.000000  0.000000
1  0.057767  0.000000  0.000000
2  0.398779  0.000000  0.025354
3  0.632846  0.000000  0.113368
4 -0.637273  1.049105  0.958093
5  0.020529  0.520461  0.738375
6 -1.149914  1.244016  1.318667

In [15]:
# use a different fill value for each column
df.fillna({1: 0.5, 2:0})

0         1         2
0  0.265736  0.500000  0.000000
1  0.057767  0.500000  0.000000
2  0.398779  0.500000  0.025354
3  0.632846  0.500000  0.113368
4 -0.637273  1.049105  0.958093
5  0.020529  0.520461  0.738375
6 -1.149914  1.244016  1.318667

In [16]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df

0         1         2
0  0.534444 -0.581895  0.504247
1 -0.211272  0.494746 -0.441445
2 -0.583260 -1.091152  1.598232
3  0.311348 -1.448825  0.342014
4 -0.901539  0.998107 -0.862463
5 -1.104927 -0.165063  0.100167

In [17]:
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.534444 -0.581895  0.504247
1 -0.211272  0.494746 -0.441445
2 -0.583260       NaN  1.598232
3  0.311348       NaN  0.342014
4 -0.901539       NaN       NaN
5 -1.104927       NaN       NaN

In [18]:
df.ffill(limit=2)

0         1         2
0  0.534444 -0.581895  0.504247
1 -0.211272  0.494746 -0.441445
2 -0.583260  0.494746  1.598232
3  0.311348  0.494746  0.342014
4 -0.901539       NaN  0.342014
5 -1.104927       NaN  0.342014

In [19]:
# filling missing data with the mean
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### DATA TRANSFORMATION

In [20]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [21]:
# boolean series specifying if each row is duplicated
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [22]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [23]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [24]:
# drop duplicates based on only a specified column or columns
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [25]:
# keep the last duplicate and drop previous occurences
data.drop_duplicates(subset=["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [26]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [27]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [28]:
data['animal'] = data['food'].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [29]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [30]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [31]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [32]:
data.replace({-999: np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [33]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [34]:
def transform(x):
    return x[:4].upper()


In [35]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [36]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [37]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [38]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [39]:
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [40]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [41]:
# parenthesis is not included and bracket is included
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [42]:
# to change which side is included pass right = False
age_categories = pd.cut(ages, bins, right=False)
age_categories

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [43]:
group_names = ["Youth", "YoundAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)


['Youth', 'Youth', 'Youth', 'YoundAdult', 'Youth', ..., 'YoundAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoundAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoundAdult' < 'MiddleAged' < 'Senior']

In [44]:
data = np.random.uniform(size=20)
data

array([0.80130027, 0.45564362, 0.6359922 , 0.50384169, 0.08792736,
       0.69286441, 0.07925251, 0.73049329, 0.46234382, 0.67091341,
       0.63904495, 0.87675686, 0.84605405, 0.10498178, 0.61605527,
       0.62981682, 0.51935065, 0.80175222, 0.55001767, 0.05129878])

In [45]:
# compute equal length bins 
pd.cut(data, 4, precision=2)

[(0.67, 0.88], (0.26, 0.46], (0.46, 0.67], (0.46, 0.67], (0.05, 0.26], ..., (0.46, 0.67], (0.46, 0.67], (0.67, 0.88], (0.46, 0.67], (0.05, 0.26]]
Length: 20
Categories (4, interval[float64, right]): [(0.05, 0.26] < (0.26, 0.46] < (0.46, 0.67] < (0.67, 0.88]]

In [46]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2)

In [47]:
quartiles.value_counts()

(-3.1999999999999997, -0.63]    250
(-0.63, 0.041]                  250
(0.041, 0.78]                   250
(0.78, 3.24]                    250
Name: count, dtype: int64

In [48]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data

0         1         2         3
0    1.012570  1.087251  0.403311 -1.631629
1    1.319374  0.544732 -0.236974  0.518038
2    0.712253  0.102744 -0.813522  0.552452
3   -1.024578 -0.990745 -0.955074  1.003333
4   -2.184550  0.397423  0.437189 -0.577560
..        ...       ...       ...       ...
995 -2.693386 -0.082454  0.284047  0.038387
996  0.301798 -0.267254 -0.645052  0.430125
997  0.500836 -0.360981  0.160837 -1.791560
998 -0.405827 -2.460052 -1.942312 -0.967221
999 -1.989483  0.828626 -0.282411  0.387704

[1000 rows x 4 columns]

In [49]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.020697    -0.024259     0.006526    -0.001616
std       1.001693     0.983840     1.034659     1.019410
min      -3.738292    -2.735331    -3.300701    -2.821942
25%      -0.669779    -0.697372    -0.708048    -0.715449
50%       0.022160    -0.004807    -0.013924     0.005420
75%       0.703791     0.631933     0.691143     0.682896
max       3.012871     3.405531     3.453366     3.143602

In [50]:
col = data[2]
col

0      0.403311
1     -0.236974
2     -0.813522
3     -0.955074
4      0.437189
         ...   
995    0.284047
996   -0.645052
997    0.160837
998   -1.942312
999   -0.282411
Name: 2, Length: 1000, dtype: float64

In [51]:
col[col.abs() > 3]

775   -3.300701
951    3.453366
Name: 2, dtype: float64

In [52]:
data[(data.abs() > 3).any(axis=1)]

0         1         2         3
188  0.273554  3.405531 -0.486551  1.381493
325  1.363086 -0.582005 -0.151894  3.081449
462 -3.738292 -0.538547  1.661418 -0.980279
492  1.970264  3.268092 -1.217287  0.316239
775  0.870260 -1.137545 -3.300701  0.199574
890 -3.340699  1.255451  0.167519 -0.304584
923  3.012871 -1.027372  1.227515 -1.457978
930  1.520127  0.326601  0.922905  3.143602
951  0.456939  0.318737  3.453366 -0.403965

In [53]:
# cap values -3 < x < 3
data[data.abs() > 3] = np.sign(data) * 3
data.describe()


0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021763    -0.024933     0.006373    -0.001841
std       0.998060     0.981645     1.032326     1.018733
min      -3.000000    -2.735331    -3.000000    -2.821942
25%      -0.669779    -0.697372    -0.708048    -0.715449
50%       0.022160    -0.004807    -0.013924     0.005420
75%       0.703791     0.631933     0.691143     0.682896
max       3.000000     3.000000     3.000000     3.000000

In [54]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [55]:
sampler = np.random.permutation(5)
sampler

array([2, 3, 4, 0, 1])

In [56]:
df.take(sampler)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [57]:
df.iloc[sampler]

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [58]:
column_sampler = np.random.permutation(7)
column_sampler

array([4, 3, 2, 1, 5, 0, 6])

In [59]:
df.take(column_sampler, axis=1)

4   3   2   1   5   0   6
0   4   3   2   1   5   0   6
1  11  10   9   8  12   7  13
2  18  17  16  15  19  14  20
3  25  24  23  22  26  21  27
4  32  31  30  29  33  28  34

In [60]:
df.sample(n=3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [61]:
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n=10, replace=True)

0    5
4    4
1    7
0    5
1    7
0    5
3    6
4    4
0    5
4    4
dtype: int64

### COMPUTING INDICATOR OR DUMMY VARIABLES
indicator matrix is where a column with k distict values is a DataFrame with<br>
k columns containing 0s and 1s

In [62]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "c", "b"], "data1": range(6)} )
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   c      4
5   b      5

In [63]:
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False  False   True
5  False   True  False

In [64]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False  False   True
5  False   True  False

In [65]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("datasets/movielens/movies.dat", sep="::", header=None, names=mnames, engine="python")
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [66]:
dummies = movies['genres'].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [67]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[:10, :10]

movie_id                               title                        genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   
5         6                         Heat (1995)         Action|Crime|Thriller   
6         7                      Sabrina (1995)                Comedy|Romance   
7         8                 Tom and Huck (1995)          Adventure|Children's   
8         9                 Sudden Death (1995)                        Action   
9        10                    GoldenEye (1995)     Action|Adventure|Thriller   

   Genre_Action  Genre_Adventure  Genre_Animation  Genre_Children's  \
0             0                0                1                 1   
1             0                1                0                 1   
2             0                0                0                 0   
3             0                0                0                 0   
4             0                0                0                 0   
5             1                0                0                 0   
6             0                0                0                 0   
7             0                1                0                 1   
8             1                0                0                 0   
9             1                1                0                 0   

   Genre_Comedy  Genre_Crime  Genre_Documentary  
0             1            0                  0  
1             0            0                  0  
2             1            0                  0  
3             1            0                  0  
4             1            0                  0  
5             0            1                  0  
6             1            0                  0  
7             0            0                  0  
8             0            0                  0  
9             0            0                  0

In [68]:
np.random.seed(12345)

In [69]:
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [70]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

### EXTENSION DATA TYPES
history -> when there was missing data, pandas converted it to float64 and np.nan for null values<br>
datasets with a lot of strings, intervals, timedeltas, amd timestamps were computationally expensive<br>
support for new data types that are not natively handled by NumPy<br>


### STRING MANIPULATION

In [71]:
val = "a,b,  guildo"
val.split(",")

['a', 'b', '  guildo']

In [72]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guildo']

In [73]:
first, second, third = pieces
second

'b'

In [74]:
first + "::" + second + "::" + third

'a::b::guildo'

In [75]:
"::".join(pieces)

'a::b::guildo'

In [76]:
"guildo" in val

True

In [77]:
val.index(',')

1

In [78]:
val.find(":")

-1

In [79]:
val.count(",")

2

In [80]:
val.replace(",", "::")

'a::b::  guildo'

### REGULAR EXPRESSIONS
a way to search or match string patterns in text<br>
pattern matching, substitution, and splitting<br>

In [81]:
import re
# \s+ one or more whitespace characters
text = "foo    bar\t baz  \tqux"
re.split("\s+", text)


['foo', 'bar', 'baz', 'qux']

In [82]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [83]:
# all patterns matching the regex
regex.findall(text)

['    ', '\t ', '  \t']

In [84]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [85]:
# first occurence
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [86]:
print(regex.match(text))
# wil only return if the pattern occurs at the start of the string

None


In [87]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [88]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [89]:
m = regex.match("wes@bright.net")
m.groups()

('wes', 'bright', 'net')

In [90]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

\1 means first matched group<br>
\2 means second matched group<br>
etc

In [91]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [92]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}

In [93]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [94]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [95]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [96]:
data_as_string_ext = data.astype('string')
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [97]:
data_as_string_ext.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [98]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [99]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [100]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [101]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [102]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

### CATEGORICAL DATA

In [103]:
rng = np.random.default_rng(12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [104]:
bins = pd.qcut(draws, 4, labels=["Q1", "Q2", "Q3", "Q4"])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [105]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [106]:
bins = pd.Series(bins, name='quartile')
bins

0      Q1
1      Q4
2      Q1
3      Q2
4      Q2
       ..
995    Q3
996    Q3
997    Q2
998    Q3
999    Q2
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [107]:
results = pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index()
results

C:\Users\andre\AppData\Local\Temp\ipykernel_17352\1292847854.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results = pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index()


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [108]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [109]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [110]:
categories = labels.astype('category')

In [111]:
labels.memory_usage(deep=True)

600000128

In [112]:
categories.memory_usage(deep=True)

10000540

In [114]:
%time _ = labels.astype('category')

CPU times: total: 109 ms
Wall time: 232 ms


In [115]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [116]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [117]:
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [118]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [119]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [120]:
# dummies or one hot encoding
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True